my.greeting: Welcome to slimdaddy's haven from default
list.values: One,Two,Three

db:
  Values: "{connectionString: 'http://___', userName: 'slim', password: 'pass'}"


management.endpoints.web.exposure.include: "*"

server:
  port: 8080

spring.profiles.active: test
spring:
  config:
    import: optional:configserver:http://localhost:8082

  cloud:
    config:
      uri: http://localhost:8082
  application:
    name: spring-boot-config

